"""fk_tipo_movimiento

Revision ID: a9df6b25819e
Revises: c7741cc08dc6
Create Date: 2026-09-08 13:44:07.406312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9df6b25819e'
down_revision: Union[str, None] = 'c7741cc08dc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'transacciones', 'tipos_movimiento', ['tipo'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transacciones', type_='foreignkey')
    # ### end Alembic commands ###
