"""Crear tabla tipos_movimiento

Revision ID: c7741cc08dc6
Revises: 6a3584dc80f9
Create Date: 2026-09-07 23:02:52.383057

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c7741cc08dc6"
down_revision: Union[str, None] = "6a3584dc80f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tipos_movimiento",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("etiqueta", sa.String(), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column("es_ingreso", sa.Boolean(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tipos_movimiento_id"), "tipos_movimiento", ["id"], unique=False
    )
    op.execute("""
        INSERT INTO tipos_movimiento (id, etiqueta, color, es_ingreso, activo) VALUES
        ('ingreso', 'Ingreso', '#10B981', true, true),
        ('gasto_fijo', 'Gasto Fijo', '#EF4444', false, true),
        ('gasto_variable', 'Gasto Variable', '#F59E0B', false, true),
        ('inversion', 'Inversión', '#3B82F6', false, true),
        ('deuda', 'Deuda', '#6366F1', false, true)
        ON CONFLICT (id) DO NOTHING;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tipos_movimiento_id"), table_name="tipos_movimiento")
    op.drop_table("tipos_movimiento")
    # ### end Alembic commands ###
