"""crear_tabla_categorias_movimiento

Revision ID: fcc138ece66d
Revises: a9df6b25819e
Create Date: 2026-09-14 10:03:51.339742

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fcc138ece66d"
down_revision: Union[str, None] = "a9df6b25819e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categorias_movimiento",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("tipo_id", sa.String(), nullable=False),
        sa.Column("activa", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tipo_id"],
            ["tipos_movimiento.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_categorias_movimiento_id"),
        "categorias_movimiento",
        ["id"],
        unique=False,
    )
    op.add_column(
        "transacciones", sa.Column("categoria_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_transacciones_categoria_id"),
        "transacciones",
        ["categoria_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transacciones_titulo"), "transacciones", ["titulo"], unique=False
    )
    op.create_foreign_key(
        None, "transacciones", "categorias_movimiento", ["categoria_id"], ["id"]
    )
    op.drop_column("transacciones", "categoria")

    op.execute("""
        INSERT INTO categorias_movimiento (nombre, activa, tipo_id) VALUES
        ('Nómina', true, 'ingreso'),
        ('Freelance', true, 'ingreso'),
        ('Otros Ingresos', true, 'ingreso'),
        ('Alquiler / Hipoteca', true, 'gasto_fijo'),
        ('Suministros (Luz, Agua, Gas)', true, 'gasto_fijo'),
        ('Internet y Móvil', true, 'gasto_fijo'),
        ('Seguros', true, 'gasto_fijo'),
        ('Supermercado', true, 'gasto_variable'),
        ('Ocio y Restaurantes', true, 'gasto_variable'),
        ('Transporte / Gasolina', true, 'gasto_variable'),
        ('Ropa y Compras', true, 'gasto_variable'),
        ('Fondos Indexados', true, 'inversion'),
        ('Acciones / Crypto', true, 'inversion'),
        ('Préstamo Coche', true, 'deuda'),
        ('Tarjeta de Crédito', true, 'deuda')
        ON CONFLICT DO NOTHING;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transacciones",
        sa.Column(
            "categoria", sa.VARCHAR(length=80), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "transacciones", type_="foreignkey")
    op.drop_index(op.f("ix_transacciones_titulo"), table_name="transacciones")
    op.drop_index(op.f("ix_transacciones_categoria_id"), table_name="transacciones")
    op.drop_column("transacciones", "categoria_id")
    op.drop_index(
        op.f("ix_categorias_movimiento_id"), table_name="categorias_movimiento"
    )
    op.drop_table("categorias_movimiento")
    # ### end Alembic commands ###
